### ISSUE TITLE
Exception generating tests with code in nested files

### ISSUE THREAD

**Issue by Hefaistos68** [mattwhitfield/Unitverse#217]
**Describe the bug**
When you have C# files with nested files, then the top parent seems to be seen as folder instead of a source file, and Unitverse tries to access a folder with the name of the top parent.
In my case the structure is:
```
DateTimeExtencions.cs (top parent)
- DateTimeExtensions.FirstLast.cs
- DateTimeExtensions.othernestedfiles.cs
```
When I tried to generate the tests for the `DateTimeExtensions.FirstLast.cs` file, I got the below exception.

```
Unitverse

Exception raised
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\dev\Repos\MoreDateTime\MoreDateTime.Test\Extensions\DateTimeExtensions.cs\DateTimeExtensions.FirstLastTests.cs'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Unitverse.Helper.CodeGenerator.AddTargetItem(IUnitTestGeneratorPackage package, GenerationItem generationItem, Boolean withActivation, IMessageLogger logger) in D:\a\Unitverse\Unitverse\src\Unitverse\Helper\CodeGenerator.cs:line 124
   at Unitverse.Helper.CodeGenerator.<>c__DisplayClass0_0.<GenerateCodeAsync>b__0() in D:\a\Unitverse\Unitverse\src\Unitverse\Helper\CodeGenerator.cs:line 72
   at Unitverse.Helper.Attempt.Action(Action action, IUnitTestGeneratorPackage package) in D:\a\Unitverse\Unitverse\src\Unitverse\Helper\Attempt.cs:line 18

```

**Additional context**
VS 2022 17.5.3, C# .NET6 solution, file nesting for Web enabled in solution explorer

**Comment by mattwhitfield** [comment]
I can't repro this exactly - there's definitely some weird behaviour around this - but could you provide a test project that exhibits this?

**Comment by Hefaistos68** [comment]
I think this is a result of issue #216 , It all has to do how the files are nested in the solution explorer. Guess MS changed a few things on how to access the project structure in respect to nesting, as this is now freely configurable.
Will try to make up a test project.

**Comment by Hefaistos68** [comment]
Cant repro it either, but it definitely has to do with deleting the folder (*.cs) it created (erroneously) and putting a file with the same name in place.

**Comment by mattwhitfield** [comment]
OK, so I traced this through, and I think it is a result of the file caching internal to Visual Studio. Sometimes you can get similar effects if you add a class where the file exists on disk, delete the file and then try and create the class again, and VS gets confused and you get an error.

It is pretty rare these days, and I have modified the flow would cause it in Unitverse - so I think the right thing to do is what it currently does - show an error.

What do you think?

**Comment by Hefaistos68** [comment]
No idea, if its VS related maybe its ok not to mess with it. Just thought it was somehow related to the folder that unitverse created erroneously with those nested files. Keep it in reserve, maybe its void anyway with the changes for nesting you did.

**Comment by mattwhitfield** [comment]
OK, will close this for now. If you see any issues with the changes to nested file handling, let's cover those in the other issue 👍
